name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
        
  build:
  
    

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: login to docker_hub
      uses: docker/login-action@v3 
      with: 
        username: ${{secrets.DOKCERHUB_LOGIN}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    - name: Setup BuildX
      uses: docker/setup-buildx-action@v3
    - name: Docker build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true 
        tags: ${{secrets.DOKCERHUB_LOGIN}}/my-api:latest
    
    
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: pull and deploy 
        run: docker compose pull && docker compose up -d
      - name: testing
        run: |
          docker compose exec -T mytest_api pip3 install pytest
          docker compose exec -T mytest_api pytest
          
        
      
    
      
      
