name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: login to docker_hub
      uses: docker/login-action@v3 
      with: 
        username: ${{secret.DOKCERHUB_LOGIN}}
        password: ${{secret.DOCKERHUB_TOKEN}}
    - name: Setup BuildX
      uses: docker/setup-buildx-action@v3
    - name: Docker build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true 
        tags: ${{secret.DOKCERHUB_LOGIN}}/my-api:latest
      
